CREATE TABLE `db_dinamics` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`dinamic` TEXT NOT NULL DEFAULT '',
	`type` TEXT NOT NULL DEFAULT '',
	`text` TEXT NOT NULL DEFAULT ''
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
