CREATE TABLE `db_forms` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`tbl` TEXT NOT NULL DEFAULT '',
	`row` TEXT NOT NULL DEFAULT '',
	`name` TEXT NOT NULL DEFAULT '',
	`type` TEXT NOT NULL DEFAULT '',
	`needed` INTEGER NOT NULL DEFAULT '0',
	`unique` INTEGER NOT NULL DEFAULT '0',
	`position` INTEGER NOT NULL DEFAULT '0',
	`noedit` INTEGER NOT NULL DEFAULT '0'
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
