CREATE TABLE `db_lists` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`tbl` TEXT NOT NULL DEFAULT '',
	`row` TEXT NOT NULL DEFAULT '',
	`name` TEXT NOT NULL DEFAULT '',
	`type` TEXT NOT NULL DEFAULT '',
	`edit` INTEGER NOT NULL DEFAULT '0',
	`size` TEXT NOT NULL DEFAULT '',
	`position` INTEGER NOT NULL DEFAULT '0'
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
