CREATE TABLE `db_notes` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`user` TEXT NOT NULL DEFAULT '',
	`note` TEXT NOT NULL DEFAULT '',
	`enabled` INTEGER NOT NULL DEFAULT '0',
	`alltime` INTEGER NOT NULL DEFAULT '0'
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
