CREATE TABLE `db_perms` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`user` TEXT NOT NULL DEFAULT '',
	`tbl` TEXT NOT NULL DEFAULT '',
	`role` TEXT NOT NULL DEFAULT '',
	`allow` TEXT NOT NULL DEFAULT ''
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
