CREATE TABLE `db_sessions` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`sess_file` TEXT NOT NULL DEFAULT '',
	`sess_data` TEXT NOT NULL DEFAULT '',
	`sess_time` INTEGER NOT NULL DEFAULT '0'
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
