CREATE TABLE `def_icons` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`icon` TEXT NOT NULL DEFAULT '',
	`icon_file` TEXT NOT NULL DEFAULT '',
	`icon_size` INTEGER NOT NULL DEFAULT '0',
	`icon_type` TEXT NOT NULL DEFAULT ''
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
