CREATE TABLE `tbl_response` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`id_queue` INTEGER NOT NULL DEFAULT '0',
	`response` LONGTEXT NOT NULL DEFAULT '',
	`hora` TIME NOT NULL DEFAULT '00:00:00',
	`fecha` DATE NOT NULL DEFAULT '0000-00-00'
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
