CREATE TABLE `tbl_files` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`tag` TEXT NOT NULL DEFAULT '',
	`image` INTEGER NOT NULL DEFAULT '0',
	`file` TEXT NOT NULL DEFAULT '',
	`file_file` TEXT NOT NULL DEFAULT '',
	`file_size` INTEGER NOT NULL DEFAULT '0',
	`file_type` TEXT NOT NULL DEFAULT ''
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
