CREATE TABLE `tbl_config` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`param` TEXT NOT NULL DEFAULT '',
	`value` TEXT NOT NULL DEFAULT '',
	`type` TEXT NOT NULL DEFAULT '',
	`title` TEXT NOT NULL DEFAULT '',
	`minval` TEXT NOT NULL DEFAULT '',
	`maxval` TEXT NOT NULL DEFAULT ''
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
