CREATE TABLE `tbl_mailing` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`host` TEXT NOT NULL DEFAULT '',
	`user` TEXT NOT NULL DEFAULT '',
	`pass` TEXT NOT NULL DEFAULT '',
	`from` TEXT NOT NULL DEFAULT '',
	`fromname` TEXT NOT NULL DEFAULT ''
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
