CREATE TABLE `tbl_queue` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`host` TEXT NOT NULL DEFAULT '',
	`user` TEXT NOT NULL DEFAULT '',
	`pass` TEXT NOT NULL DEFAULT '',
	`from` TEXT NOT NULL DEFAULT '',
	`fromname` TEXT NOT NULL DEFAULT '',
	`to` LONGTEXT NOT NULL DEFAULT '',
	`subject` TEXT NOT NULL DEFAULT '',
	`body` TEXT NOT NULL DEFAULT '',
	`status` INTEGER NOT NULL DEFAULT '0',
	`hora` TIME NOT NULL DEFAULT '00:00:00',
	`fecha` DATE NOT NULL DEFAULT '0000-00-00',
	`fichero` TEXT NOT NULL DEFAULT '',
	`fichero_file` TEXT NOT NULL DEFAULT '',
	`fichero_size` INTEGER NOT NULL DEFAULT '0',
	`fichero_type` TEXT NOT NULL DEFAULT ''
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
