CREATE TABLE `tbl_google` (
	`id` INTEGER PRIMARY KEY /*MYSQL AUTO_INCREMENT *//*SQLITE AUTOINCREMENT */,
	`lat` TEXT NOT NULL DEFAULT '',
	`lon` TEXT NOT NULL DEFAULT '',
	`logo` TEXT NOT NULL DEFAULT '',
	`logo_file` TEXT NOT NULL DEFAULT '',
	`logo_size` INTEGER NOT NULL DEFAULT '0',
	`logo_type` TEXT NOT NULL DEFAULT '',
	`texto` TEXT NOT NULL DEFAULT '',
	`titulo` TEXT NOT NULL DEFAULT ''
) /*MYSQL ENGINE=MyISAM CHARSET=utf8 */;
