<?php
/*
 ____  _     _        ___  ____
|  _ \| |__ (_)_ __  / _ \/ ___|
| |_) | '_ \| | '_ \| | | \___ \
|  _ <| | | | | | | | |_| |___) |
|_| \_\_| |_|_|_| |_|\___/|____/

RhinOS: Framework to develop Rich Internet Applications
Copyright (C) 2007-2016 by Josep Sanz Campderrós
More information in http://www.saltos.org or info@saltos.org

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
$_LANG=array("lang"=>"en");
// ABOUT
$_LANG["about_copyright"]="This software is distributed under the terms of the licence GPL-3.0:";
$_LANG["about_link_project"]="Access to the project";
$_LANG["about_link_project_title"]="To access the website of the project";
$_LANG["about_software"]="This software uses the following components:";
$_LANG["about_server_base"]="Server base:";
$_LANG["about_php_plugins"]="PHP plug-ins:";
$_LANG["about_javascript_base"]="Javascript base:";
$_LANG["about_jquery_plugins"]="JQuery plugins:";
$_LANG["about_server_plugins"]="Server plugins:";
$_LANG["about_vxinfo"]="<b>Note</b>: (*) Some projects do not specify the specific version of the licence that they employ";
$_LANG["about_button_return"]="Return";
$_LANG["about_button_return_title"]="To return to the main menu";
$_LANG["about_developers"]="Developers";
$_LANG["about_translators"]="Translations";
// CATALOG
$_LANG["catalog_show_icons_search"]="Show icons with the text:";
$_LANG["catalog_button_ok"]="Update";
$_LANG["catalog_button_ok_title"]="It shows all icons<br/>that acomplish the filter";
$_LANG["catalog_button_all"]="Show all";
$_LANG["catalog_button_all_title"]="It shows all icons<br/>removing the current filter";
$_LANG["catalog_button_cancel"]="Cancel";
$_LANG["catalog_button_cancel_title"]="It return to the main menu";
// CONNECT
$_LANG["connect_checkdemo_unknown_type"]="Unknown check_demo type: ";
$_LANG["connect_message_file_not_found"]="File not found: ";
$_LANG["connect_message_dir_not_found"]="Directory not found: ";
$_LANG["connect_message_dir_not_writable"]="Directory not writable: ";
$_LANG["connect_message_unknown_type"]="Unknown type ";
$_LANG["connect_message_db_schema_noedit"]="Field noedit not found in the db_forms table";
$_LANG["connect_message_db_schema_about"]="Add this lines in the config editor (db_tables section)<br/>ROW \"about.php\",\"About RhinOS\",\"About RhinOS\",\"102\",\"khelpcenter.png\"";
// CONTACT
$_LANG["contact_field_name"]="Name";
$_LANG["contact_field_email"]="Email";
$_LANG["contact_field_comments"]="Comments";
$_LANG["contact_button_ok"]="Send";
$_LANG["contact_button_ok_title"]="After filling all data form,<br/>push this button";
$_LANG["contact_button_cancel"]="Cancel";
$_LANG["contact_button_cancel_title"]="It cancels the submit";
$_LANG["contact_message_full"]="You must enter all fields in order to be able to send the mail to the technical support";
$_LANG["contact_message_error"]="An error occurred sending the e-mail to ";
$_LANG["contact_message_ok"]="An e-mail has been sent with data of the form to ";
// DB_SPEC
$_LANG["db_spec_button_ok"]="Update";
$_LANG["db_spec_button_ok_title"]="Clicking this button, you update the admin configuration";
$_LANG["db_spec_button_cancel"]="Cancel";
$_LANG["db_spec_button_cancel_title"]="It cancels the admin configuration update";
$_LANG["db_spec_field_file"]="File:";
$_LANG["db_spec_message_file_detected"]="Detected the existence of the file ";
$_LANG["db_spec_message_error"]="An error occurred when uploading the file to the server";
$_LANG["db_spec_message_ok"]="Configuration updated succesfully";
$_LANG["db_spec_message_set_database"]="The DATABASE tag has already been defined earlier";
$_LANG["db_spec_message_diff_database"]="The DATABASE tag defers with the name of the database ";
$_LANG["db_spec_message_null_database"]="The DATABASE tag can not be null";
$_LANG["db_spec_message_null_table"]="The TABLE tag can not be null";
$_LANG["db_spec_message_set_spec"]="The SPEC tag has already been defined earlier";
$_LANG["db_spec_message_null_spec"]="The SPEC tag can not be null";
// EXPORT
$_LANG["export_message_unallowed"]="This page must be called from a list";
$_LANG["export_message_not_data"]="There are no data to export";
$_LANG["export_label_list_of"]="List of ";
$_LANG["export_label_page_number"]="Page ";
$_LANG["export_label_not_file"]="[There is no file]";
$_LANG["export_label_not_photo"]="[There is no photo]";
$_LANG["export_label_yes"]="Yes";
$_LANG["export_label_not"]="No";
$_LANG["export_label_photo_not_available"]="[Image unavailable]";
$_LANG["export_title_of"]="Export data of ";
$_LANG["export_output_format"]="Output format:";
$_LANG["export_output_format_pdf"]="(PDF) Acrobat Reader";
$_LANG["export_output_format_xls5"]="(XLS) Microsoft Excel 5";
$_LANG["export_output_format_xls7"]="(XLS) Microsoft Excel 2007";
$_LANG["export_output_format_csv"]="(CSV) Comma-separated text";
$_LANG["export_output_format_zip"]="(ZIP) Zip with all images";
$_LANG["export_separator_field"]="Fields separator:";
$_LANG["export_separator_field_1"]="(;) Semicolon";
$_LANG["export_separator_field_2"]="(,) Comma";
$_LANG["export_separator_field_3"]="(:) Two points";
$_LANG["export_separator_field_4"]="(.) Point";
$_LANG["export_first_line"]="Name of the fields:";
$_LANG["export_paginate_model"]="Pagination mode:";
$_LANG["export_paginate_model_1"]="One record in each page";
$_LANG["export_paginate_model_0"]="Maximum records in each page";
$_LANG["export_fields_to_export"]="Fields to be exported:";
$_LANG["export_button_ok"]="Export";
$_LANG["export_button_ok_title"]="Clicking here, you make the export";
$_LANG["export_button_sel"]="Selection";
$_LANG["export_button_sel_title"]="Selects all fields<br/>or does not select none";
$_LANG["export_button_cancel"]="Cancel";
$_LANG["export_button_cancel_title"]="It cancels the current export";
$_LANG["export_first_register"]="Start from register number";
$_LANG["export_total_registers"]="Total of registers to be exported";
// FORM
$_LANG["form_config_not_found"]="Configuration not found for this form";
$_LANG["form_message_form_error"]="Errors founded in the form";
// FUNCTIONS
$_LANG["functions_closebody_ismsie"]="To improve your experience with this application, I recommend the following web browsers:";
$_LANG["functions_putselect_default_option"]="Select an option";
$_LANG["functions_putselect_not_options"]="[There is no option]";
$_LANG["functions_putselect_big_options"]="Filter for the list: ";
$_LANG["functions_putselect_big_options_number"]=" results";
$_LANG["functions_putselect_big_options_title"]="Attention!!!";
$_LANG["functions_putselect_big_options_description"]="The list contains too many results<br/>(specifically #numero#) and that is why it, he should<br/>give some filter to obtain<br/>a list but short";
$_LANG["functions_putselect_ok_options_title"]="Congratulations";
$_LANG["functions_putselect_ok_options_description"]="With the entered filter, have found<br/>#numero# results and when not exceeding the #maximo#<br/>results, it can display the results";
$_LANG["functions_putselect_not_options_title"]="Attention!!!";
$_LANG["functions_putselect_not_options_description"]="The entered filter is too restrictive one<br/>and we have not found results<br/>that acomplish it";
$_LANG["functions_putselect_big_options_message"]="Please, apply a more restrictive filter";
$_LANG["functions_putselect_button_search"]="Search";
$_LANG["functions_putmultiselect_button_add"]="Select";
$_LANG["functions_putmultiselect_button_add_title"]="Selects marked elements";
$_LANG["functions_putmultiselect_button_del"]="Unselect";
$_LANG["functions_putmultiselect_button_del_title"]="Unselects marked elements";
$_LANG["functions_putmultiselect_not_options"]="[There is no option]";
$_LANG["functions_putmultiselect_big_options"]="Filter for the list: ";
$_LANG["functions_putmultiselect_big_options_number"]=" results";
$_LANG["functions_putmultiselect_big_options_title"]="Attention!!!";
$_LANG["functions_putmultiselect_big_options_description"]="The list contains too many results<br/>(specifically #numero#) and that is why it, he should<br/>give some filter to obtain<br/>a list but short";
$_LANG["functions_putmultiselect_ok_options_title"]="Congratulations";
$_LANG["functions_putmultiselect_ok_options_description"]="With the entered filter, have found<br/>#numero# results and when not exceeding the #maximo#<br/>results, can display the results";
$_LANG["functions_putmultiselect_not_options_title"]="Attention!!!";
$_LANG["functions_putmultiselect_not_options_description"]="The entered filter is too restrictive one<br/>and we have not found no result<br/>that acomplish it";
$_LANG["functions_putmultiselect_button_search"]="Search";
$_LANG["functions_putfile_name"]="Name:";
$_LANG["functions_putfile_size"]="Size:";
$_LANG["functions_putfile_type"]="Type:";
$_LANG["functions_putfile_download"]="Download the file";
$_LANG["functions_putfile_delete"]="Delete this file";
$_LANG["functions_putfile_not_file"]="[There is no file]";
$_LANG["functions_putfile_demo_disabled"]="(Feature disabled in DEMO mode)";
$_LANG["functions_putphoto_name"]="Name:";
$_LANG["functions_putphoto_size"]="Size:";
$_LANG["functions_putphoto_type"]="Type:";
$_LANG["functions_putphoto_download"]="Download the photo";
$_LANG["functions_putphoto_preview"]="Preview:";
$_LANG["functions_putphoto_delete"]="Delete this photo";
$_LANG["functions_putphoto_not_photo"]="[There is no photo]";
$_LANG["functions_putphoto_demo_disabled"]="(Feature disabled in DEMO mode)";
$_LANG["functions_putboolean_yes"]="Yes";
$_LANG["functions_putboolean_not"]="No";
$_LANG["functions_getboolean_alt"]="Change the value of this field";
$_LANG["functions_getboolean_yes"]="Yes";
$_LANG["functions_getboolean_not"]="No";
$_LANG["functions_getlink_not_file"]="[There is no file]";
$_LANG["functions_getlink_name"]="Name: ";
$_LANG["functions_getlink_size"]="Size: ";
$_LANG["functions_getlink_type"]="Type: ";
$_LANG["functions_getselect_default_option"]="Select an option";
$_LANG["functions_getselect_not_options"]="[Not option selected]";
$_LANG["functions_getmultiselect_not_options"]="[No option selected]";
$_LANG["functions_puterrores_warning"]="Attention:";
$_LANG["functions_puterrores_error"]="Error:";
$_LANG["functions_reparaformconfig_error"]="Attention: Internal error of the application";
$_LANG["functions_finddependencies_error"]="Linked record in ";
$_LANG["functions_msgbox_title"]="Message of the system";
$_LANG["functions_msgbox_button_close"]="Close";
$_LANG["functions_msgbox_button_return"]="Return";
$_LANG["functions_msgbox_button_continue"]="Continue";
$_LANG["functions_putfloatmenu_title"]="MENU";
$_LANG["functions_showdatadinamic_unknown_type"]="Unknown dinamic type ";
$_LANG["functions_putcolor_button_open"]="Colours";
$_LANG["functions_putcolor_button_open_title"]="Click here to open the color widget";
$_LANG["functions_putdate_button_open"]="Calendar";
$_LANG["functions_putdate_button_open_title"]="Click here to open the calendar widget";
$_LANG["functions_putform_retype"]="Repeat ";
$_LANG["functions_putform_time_button"]="Time";
$_LANG["functions_putform_time_button_title"]="Enter the time and minutes in the format HH:MM";
$_LANG["functions_putform_field_needed"]="Required field";
$_LANG["functions_putform_field_unique"]="Unique field";
$_LANG["functions_putform_field_optional"]="Optional field";
$_LANG["functions_putform_field_readonly"]="Automatic field";
$_LANG["functions_preparebuttons_default_option"]="Select type";
$_LANG["functions_preparebuttons_button_add"]="Add";
$_LANG["functions_preparebuttons_button_add_title"]="It adds a dynamic new field";
$_LANG["functions_preparebuttons_button_delete"]="Delete";
$_LANG["functions_preparebuttons_button_delete_title"]="To delete this field";
$_LANG["functions_preparebuttons_button_moveup"]="Move up";
$_LANG["functions_preparebuttons_button_moveup_title"]="Move this field to up";
$_LANG["functions_preparebuttons_button_movedown"]="Move down";
$_LANG["functions_preparebuttons_button_movedown_title"]="Move this field to down";
$_LANG["functions_putajaxdinamic_message_max"]="You can not add more fields";
$_LANG["functions_putajaxdinamic_unknown_type"]="Unknown dinamic type ";
$_LANG["functions_putbuttons_button_create"]="Create";
$_LANG["functions_putbuttons_button_create_title"]="It creates a record with<br/>the current form data";
$_LANG["functions_putbuttons_button_update"]="Update";
$_LANG["functions_putbuttons_button_update_title"]="It updates the record with<br/>the current form data";
$_LANG["functions_putbuttons_button_create2"]="Create and return";
$_LANG["functions_putbuttons_button_create2_title"]="It creates a record with<br/>the current form data and<br/>then, returns here";
$_LANG["functions_putbuttons_button_update2"]="Update and return";
$_LANG["functions_putbuttons_button_update2_title"]="It updates the record with<br/>data of the form and<br/>returns to this screen";
$_LANG["functions_putbuttons_button_cancel"]="Cancel";
$_LANG["functions_putbuttons_button_cancel_create"]="It cancels the creation<br/>";
$_LANG["functions_putbuttons_button_cancel_update"]="It cancels the update<br/>";
$_LANG["functions_putbuttons_button_return"]="Return";
$_LANG["functions_putbuttons_button_return_title"]="To return to the previous list";
$_LANG["functions_putbuttons_button_update3"]="Edit";
$_LANG["functions_putbuttons_button_update3_title"]="It accesses the form to<br/>edit all data<br/>of this record";
$_LANG["functions_checkmultipleparameters_message_diff_error"]="The values entered in fields #campo1# and Retype #campo2# are differents";
$_LANG["functions_checkmultipleparameters_message_unique_error"]="There is a record with the same value in the field ";
$_LANG["functions_checkmultipleparameters_message_needed_error"]="The field #campo# is mandatory";
$_LANG["functions_updatedatadinamic_message_error_type"]="Unknown dinamic type ";
$_LANG["functions_updatedatadinamic_message_error_counter"]="Unknown dinamic counter ";
$_LANG["functions_getmigas_button_menu"]="Main menu";
$_LANG["functions_getmigas_button_menu_title"]="Access to the main menu";
$_LANG["functions_getmigas_button_access_to"]="Application of ";
$_LANG["functions_getmigas_button_access_to_title"]="Access to the application of ";
$_LANG["functions_getmigas_button_list"]="List of ";
$_LANG["functions_getmigas_button_list_title"]="Access to the list of ";
$_LANG["functions_getmigas_button_show"]="Enquiry of ";
$_LANG["functions_getmigas_button_show_title"]="Access to the enquiry of ";
$_LANG["functions_getmigas_button_update"]="Update of ";
$_LANG["functions_getmigas_button_update_title"]="Access to the update of ";
$_LANG["functions_getmigas_button_create"]="Creation of ";
$_LANG["functions_getmigas_button_create_title"]="Access to the creation of ";
$_LANG["functions_getmigas_button_export"]="Export of ";
$_LANG["functions_getmigas_button_export_title"]="Access to the export of ";
$_LANG["functions_getmigas_button_login"]="Access to the application";
$_LANG["functions_getmigas_button_login_title"]="This screen allows accessing the<br/>application using your credentials";
$_LANG["functions_getpartners_2_title"]="The SaltOS project";
$_LANG["functions_getpartners_2_description"]="Visit the project website<br/>that makes this software";
$_LANG["functions_getpartners_3_title"]="Licensed unded GPL-3.0";
$_LANG["functions_getpartners_3_description"]="This software is licensed<br/>under the GPL-3.0 license";
$_LANG["functions_getpartners_4_title"]="Powered by GNU";
$_LANG["functions_getpartners_4_description"]="RhinOS bases all its applications<br/>technology on GNU systems";
$_LANG["functions_getpartners_5_title"]="Powered by Apache";
$_LANG["functions_getpartners_5_description"]="RhinOS bases all its web applications<br/>technology on Apache";
$_LANG["functions_getpartners_6_title"]="Powered by PHP";
$_LANG["functions_getpartners_6_description"]="RhinOS bases all its web applications<br/>technology on PHP";
$_LANG["functions_getpartners_7_title"]="Powered by MySQL";
$_LANG["functions_getpartners_7_description"]="RhinOS bases all its web applications<br/>technology on MySQL";
$_LANG["functions_getpartners_8_title"]="Powered by SQLite";
$_LANG["functions_getpartners_8_description"]="RhinOS bases all its web applications<br/>technology on SQLite";
$_LANG["functions_getpartners_9_title"]="Powered by JQuery";
$_LANG["functions_getpartners_9_description"]="Rhinos technology uses JQuery and JQuery UI<br/>for web applications";
$_LANG["functions_getpartners_10_title"]="Powered by PHPJS";
$_LANG["functions_getpartners_10_description"]="Rhinos technology uses PHPJS<br/>for web applications";
$_LANG["functions_getpartners_11_title"]="Powered by FCK Editor";
$_LANG["functions_getpartners_11_description"]="RhinOS technology uses CKEditor<br/>for web applications";
$_LANG["functions_getpartners_12_title"]="Use Firefox";
$_LANG["functions_getpartners_12_description"]="From RhinOS, recommend the use of<br/>this web browser to obtain maximum<br/>loans of online applications";
$_LANG["functions_getpartners_13_title"]="Use Google Chrome";
$_LANG["functions_getpartners_13_description"]="From RhinOS, recommend the use of<br/>this web browser to obtain maximum<br/>loans of online applications";
$_LANG["functions_getloading_title"]="Loading...";
$_LANG["functions_color2dec_error"]="Unknown component on color2dec function";
$_LANG["functions_addlog_error"]="Can not open log file: ";
// GETDINAMIC
$_LANG["getdinamic_unknown_type"]="Unknown dinamic type ";
$_LANG["getdinamic_demo_disabled"]="(Feature disabled in DEMO mode)";
// GETFILTER
$_LANG["getfilter_message_error"]="Attention: internal error of the application";
// GETSELECT
$_LANG["getselect_button_date"]="Calendar";
$_LANG["getselect_button_date_title"]="It shows the date in the format DD/MM/YYYY";
$_LANG["getselect_button_time"]="Time";
$_LANG["getselect_button_time_title"]="It shows the time and minutes in the format HH:MM";
// HEAD
$_LANG["head_button_password"]="Change password";
$_LANG["head_button_password_title"]="To change your password<br/>of the application";
$_LANG["head_button_contact"]="Technical support";
$_LANG["head_button_contact_title"]="Send an e-mail to the technical support<br/>with incidences or suggestions to<br/>the system administrator";
$_LANG["head_button_about"]="About RhinOS";
$_LANG["head_button_about_title"]="Know the credits of RhinOS<br/>and components that it uses";
$_LANG["head_button_logout"]="Close session";
$_LANG["head_button_logout_title"]="It closes the current<br/>session of the application";
$_LANG["head_button_style"]="Style";
$_LANG["head_button_style_title"]="Current used style ";
$_LANG["head_confirm_logout"]="Do you want to disconnect?";
$_LANG["head_confirm_button_yes"]="Yes";
$_LANG["head_confirm_button_not"]="No";
// INTRO
$_LANG["intro_button_ok"]="Enter";
$_LANG["intro_button_ok_title"]="After putting the user and password,<br/>validate the data";
$_LANG["intro_access_denied"]="Access denied!!!";
$_LANG["intro_username"]="Username:";
$_LANG["intro_password"]="Password:";
$_LANG["intro_remember"]="Remember password in this computer:";
$_LANG["intro_demo"]="To enter in DEMO mode:";
$_LANG["intro_demo_enabled"]="DEMO mode enabled";
$_LANG["intro_demo_message"]="It has accessed in DEMO mode which consequently certain features are disabled for security reasons";
$_LANG["intro_block_admin"]="admin blocked";
$_LANG["intro_register_globals"]="Detected variable register_globals=1";
$_LANG["intro_zlib_output_compression"]="Detected variable zlib.output_compression=1";
$_LANG["intro_config_not_found"]="Applications not found";
// LIST
$_LANG["list_config_not_found"]="Configuration not found for this list";
$_LANG["list_button_create"]="Create";
$_LANG["list_button_create_title"]="Select how many records<br/>wants to create and click this button";
$_LANG["list_button_create_prefix"]="Create records: ";
$_LANG["list_button_first"]="First";
$_LANG["list_button_first_title"]="First page";
$_LANG["list_button_first_description"]="It shows the first page";
$_LANG["list_button_previous"]="Previous";
$_LANG["list_button_previous_title"]="Previous page";
$_LANG["list_button_previous_description"]="It shows the previous page";
$_LANG["list_button_next"]="Next";
$_LANG["list_button_next_title"]="Next page";
$_LANG["list_button_next_description"]="It shows the next page";
$_LANG["list_button_last"]="Last";
$_LANG["list_button_last_title"]="last page";
$_LANG["list_button_last_description"]="It shows the latest page";
$_LANG["list_button_search"]="Search";
$_LANG["list_button_search_title"]="Searchs everything that it contains<br/>the text of the search box";
$_LANG["list_button_clear"]="Clear";
$_LANG["list_button_clear_title"]="Clear text box";
$_LANG["list_button_clear_description"]="It clear all text box of the search engine";
$_LANG["list_button_clear_prefix"]="Search engine: ";
$_LANG["list_button_fullpage"]="Full listing";
$_LANG["list_button_fullpage_title"]="It shows all results in a single list (#numero# records in total)";
$_LANG["list_button_onlypage"]="Paged listing";
$_LANG["list_button_onlypage_title"]="It shows results for pages<br/>(#numero# records for page)";
$_LANG["list_label_sort_asc"]="upward";
$_LANG["list_label_sort_desc"]="downward";
$_LANG["list_button_sort"]="Order";
$_LANG["list_button_sort_title"]="Orders the current list for<br/>";
$_LANG["list_label_not_file"]="[There is no file]";
$_LANG["list_label_not_photo"]="[There is no photo]";
$_LANG["list_icon_filter"]="Filter by ";
$_LANG["list_icon_filter_title"]="It shows all records<br/>with this ";
$_LANG["list_icon_view"]="View";
$_LANG["list_icon_view_title"]="It shows all the data<br/>of this record";
$_LANG["list_icon_edit"]="Edit";
$_LANG["list_icon_edit_title"]="To edit all the data<br/>of this record";
$_LANG["list_icon_copy"]="Copy";
$_LANG["list_icon_copy_title"]="It creates a new record with<br/>all the data of this record";
$_LANG["list_icon_delete"]="Delete";
$_LANG["list_icon_delete_title"]="Deletes this record";
$_LANG["list_icon_save"]="Save";
$_LANG["list_icon_save_title"]="Save the data changed<br/>of this record";
$_LANG["list_label_not_data"]="There are no data to show";
$_LANG["list_label_not_search"]="Data not found";
$_LANG["list_icon_selall"]="Select all";
$_LANG["list_icon_selall_title"]="Mark as selected<br/>all records";
$_LANG["list_icon_selinv"]="Invert selection";
$_LANG["list_icon_selinv_title"]="Invert the selection<br/>of all records";
$_LANG["list_icon_selnone"]="Unselect all";
$_LANG["list_icon_selnone_title"]="Mark as not selected<br/>all records";
$_LANG["list_icon_selview"]="View selected";
$_LANG["list_icon_selview_title"]="It shows all the data<br/>of selected records";
$_LANG["list_icon_seledit"]="Edit selected";
$_LANG["list_icon_seledit_title"]="To edit all the data<br/>of selected records";
$_LANG["list_icon_selcopy"]="Copy selected";
$_LANG["list_icon_selcopy_title"]="It creates new records with all the<br/>data of selected records";
$_LANG["list_icon_seldelete"]="Delete selected";
$_LANG["list_icon_seldelete_title"]="Deletes all selected records";
$_LANG["list_icon_selsave"]="Save selected";
$_LANG["list_icon_selsave_title"]="Saves the changes<br/>of selected records";
$_LANG["list_label_reg_show"]="Showed records: ";
$_LANG["list_label_reg_pag"]="Records for page: ";
$_LANG["list_select_reg_show"]="Showed records";
$_LANG["list_select_reg_show_title"]="You are currently showing records<br/>of the #numero1# to the #numero2#. Select another option of this list<br/>to change of page quickly.";
$_LANG["list_select_reg_pag"]="Records for page";
$_LANG["list_select_reg_pag_title"]="Are currently been showing #numero# records<br/>for page. Select another option of this list<br/>to change the number of records for page<br/>quickly.";
$_LANG["list_button_export"]="Export current list";
$_LANG["list_button_export_title"]="You can exports the data of the current<br/>list in format PDF, Excel or CSV";
$_LANG["list_message_error"]="Errors detected";
$_LANG["list_confirm_delete"]="Do you want to delete this record?";
$_LANG["list_confirm_update"]="Do you want to update this record?";
$_LANG["list_message_selreg"]="You must select some record";
$_LANG["list_confirm_seldelete"]="Do you want to delete selected records?";
$_LANG["list_confirm_selupdate"]="Do you want to update selected records?";
$_LANG["list_confirm_biglist"]="It is going to show #numero# records. Do you want to continue?";
$_LANG["list_confirm_button_yes"]="Yes";
$_LANG["list_confirm_button_not"]="No";
// MAILER
$_LANG["mailer_invalid_address"]="Incorrect e-mail address";
// MAIN
$_LANG["main_message_denied"]="You are not authorized to perform this action";
$_LANG["main_message_maintenance"]="Page in maintenance, sorry by the inconvenience";
// PASSWORD
$_LANG["password_message_error_old"]="The old password is incorrect";
$_LANG["password_message_error_new"]="New passwords are different";
$_LANG["password_message_ok"]="Password updated succesfully";
$_LANG["password_old_password"]="Old password:";
$_LANG["password_new_password"]="New password:";
$_LANG["password_retype_new_password"]="Repeat new password:";
$_LANG["password_button_ok"]="Update";
$_LANG["password_button_ok_title"]="After putting passwords,<br/>make the update";
$_LANG["password_button_cancel"]="Cancel";
$_LANG["password_button_cancel_title"]="It cancels the update of passwords";
// PROCESS
$_LANG["process_message_error_delete_needed"]="You can not delete a record marked as necessary";
$_LANG["process_message_error_nodata"]="There are no fields to update";
$_LANG["process_message_error_unique"]="There is a record with the same value in the field ";
$_LANG["process_message_error_needed"]="The field #campo# is mandatory";
// TBL_CONFIG
$_LANG["tblconfig_title_create"]="Create a new setup parameter";
$_LANG["tblconfig_title_delete"]="Delete a setup parameter";
$_LANG["tblconfig_message_fulldata_needed"]="The parameter, type and title fields are needed for this option";
$_LANG["tblconfig_button_ok"]="Update";
$_LANG["tblconfig_button_ok_title"]="It updates the record<br/>with data of the form";
$_LANG["tblconfig_button_cancel"]="Cancel";
$_LANG["tblconfig_button_cancel_title"]="It cancels the on-going update";
$_LANG["tblconfig_label_param"]="Parameter:";
$_LANG["tblconfig_label_type"]="Type:";
$_LANG["tblconfig_option_text"]="Text";
$_LANG["tblconfig_option_integer"]="Integer";
$_LANG["tblconfig_option_real"]="Real";
$_LANG["tblconfig_label_title"]="Title:";
$_LANG["tblconfig_label_minval"]="Minimum value:";
$_LANG["tblconfig_label_maxval"]="Maximum value:";
$_LANG["tblconfig_title_managament"]="Manage the setup of your website";
$_LANG["tblconfig_label_from_min_to_max"]="between #minimo# and #maximo#";
$_LANG["tblconfig_label_from_min"]="starting from #minimo#";
$_LANG["tblconfig_label_to_max"]="until #maximo#";
$_LANG["tblconfig_error_unknown_type"]="Unknown user space config type";
$_LANG["tblconfig_message_nodata"]="There are no setup data in your website";
$_LANG["tblconfig_label_delete"]="Parameter to be deleted:";
// TBL_FILES
$_LANG["tblfiles_title_create_file"]="Create a new file or photo";
$_LANG["tblfiles_title_delete_file"]="Delete a new file or photo";
$_LANG["tblfiles_title_current_files"]="Maintenance of the files and photos of your website";
$_LANG["tblfiles_demo_disabled"]="Feature disabled in DEMO mode";
$_LANG["tblfiles_message_tag_exists"]="The tag that you are trying to create already exists";
$_LANG["tblfiles_button_ok"]="Update";
$_LANG["tblfiles_button_ok_title"]="It updates the record<br/>with data of the form";
$_LANG["tblfiles_button_cancel"]="Cancel";
$_LANG["tblfiles_button_cancel_title"]="It cancels the on-going update";
$_LANG["tblfiles_label_tag"]="Tag of the file:";
$_LANG["tblfiles_label_isfile"]="It is an image:";
$_LANG["tblfiles_label_file"]="File:";
$_LANG["tblfiles_label_delete"]="Delete file or photo:";
$_LANG["tblfiles_label_photo"]="Photo:";
$_LANG["tblfiles_message_nodata"]="There are no parametrized files in your website";
// TBL_GOOGLE
$_LANG["tblgoogle_button_ok"]="Update";
$_LANG["tblgoogle_button_ok_title"]="It updates the record<br/>with data of the form";
$_LANG["tblgoogle_button_cancel"]="Cancel";
$_LANG["tblgoogle_button_cancel_title"]="It cancels the on-going update";
$_LANG["tblgoogle_label_for"]=" for ";
$_LANG["tblgoogle_label_title"]="Googles Maps setup";
$_LANG["tblgoogle_label_lat"]="Latitude GPS:";
$_LANG["tblgoogle_label_lon"]="Length GPS:";
$_LANG["tblgoogle_label_logo"]="Logo:";
$_LANG["tblgoogle_label_text"]="Text:";
// TBL_LABELS
$_LANG["tbllabels_title_table_options"]="Options of the labels table";
$_LANG["tbllabels_title_create_tag"]="Create a new label";
$_LANG["tbllabels_title_delete_tag"]="Delete an existing label";
$_LANG["tbllabels_title_change_lang_sec"]="Change of language or section";
$_LANG["tbllabels_title_current_labels"]="Maintenance of the labels of your website";
$_LANG["tbllabels_label_option_add_sec"]="Add seccion";
$_LANG["tbllabels_label_option_del_sec"]="Delete seccion";
$_LANG["tbllabels_label_option_add_lang"]="Add language";
$_LANG["tbllabels_label_option_del_lang"]="Delete language";
$_LANG["tbllabels_message_error_lang_with_not_option"]="You must to specify the action associated to the language entered";
$_LANG["tbllabels_message_error_sec_not_lang"]="Not enter the [language of the option] for this option";
$_LANG["tbllabels_message_ok_add_sec"]="The section field has been added";
$_LANG["tbllabels_message_error_sec_exists"]="Section field already exists";
$_LANG["tbllabels_message_ok_del_sec"]="The section field has been erased";
$_LANG["tbllabels_message_error_sec_not_exists"]="Section field not found";
$_LANG["tbllabels_message_error_lang_not_found"]="You must provide [language of the option] for this option";
$_LANG["tbllabels_message_error_lang_2_chars"]="The language should have 2 carácteres";
$_LANG["tbllabels_message_ok_add_lang"]="The language has been added: ";
$_LANG["tbllabels_message_error_lang_exists"]="Language already exists: ";
$_LANG["tbllabels_message_error_lang_del_default"]="You can not remove the language [#default#]";
$_LANG["tbllabels_message_ok_del_lang"]="The language has been removed: ";
$_LANG["tbllabels_message_error_lang_not_exists"]="Language not found: ";
$_LANG["tbllabels_message_error_tag_exists"]="The tag already create exists";
$_LANG["tbllabels_button_ok"]="Update";
$_LANG["tbllabels_button_ok_title"]="Updates the record<br/>with the form data";
$_LANG["tbllabels_button_cancel"]="Cancel";
$_LANG["tbllabels_button_cancel_title"]="Cancels the on-going update";
$_LANG["tbllabels_label_literal"]="Value of the label";
$_LANG["tbllabels_label_table_options"]="Options of the table:";
$_LANG["tbllabels_label_lang_option"]="Language of the option:";
$_LANG["tbllabels_label_sec_exists"]="There are sections.";
$_LANG["tbllabels_label_sec_not_exists"]="There are no sections.";
$_LANG["tbllabels_label_current_langs"]="Current languages:";
$_LANG["tbllabels_label_notes"]="Notes: ";
$_LANG["tbllabels_label_new_literal"]="New label:";
$_LANG["tbllabels_label_new_sec"]="New section:";
$_LANG["tbllabels_label_existent_sec"]="Existing section:";
$_LANG["tbllabels_label_ishtml"]="It is a HTML field:";
$_LANG["tbllabels_label_section"]="Section:";
$_LANG["tbllabels_label_del_literal"]="Delete label:";
$_LANG["tbllabels_label_lang"]="Language:";
$_LANG["tbllabels_label_letter"]="Letter ";
$_LANG["tbllabels_message_nodata"]="This website not uses labels currently";
// TBL_MAILING
$_LANG["tblmailing_demo_disabled"]="Feature disabled in DEMO mode";
$_LANG["tblmailing_message_error"]="To send a mailing should provide all fields";
$_LANG["tblmailing_message_ok"]="The mailing has been accepted to be sent";
$_LANG["tblmailing_button_ok"]="Update";
$_LANG["tblmailing_button_ok_title"]="Updates the record<br/>with the form data";
$_LANG["tblmailing_button_cancel"]="Cancel";
$_LANG["tblmailing_button_cancel_title"]="Cancels the on-going update";
$_LANG["tblmailing_label_smtp_config"]="SMTP setup";
$_LANG["tblmailing_label_smtp_host"]="SMTP host:";
$_LANG["tblmailing_label_username"]="Username:";
$_LANG["tblmailing_label_password"]="Password:";
$_LANG["tblmailing_label_from_email"]="From email:";
$_LANG["tblmailing_label_from_name"]="From name:";
$_LANG["tblmailing_label_to"]="To:";
$_LANG["tblmailing_label_subject"]="Subject:";
$_LANG["tblmailing_label_body"]="Body:";
// TBL_USERS
$_LANG["tblusers_title_create"]="Create a new user:";
$_LANG["tblusers_title_modify"]="Modify existing users:";
$_LANG["tblusers_label_username"]="Username:";
$_LANG["tblusers_label_password"]="Password:";
$_LANG["tblusers_label_retype"]="Repeat password:";
$_LANG["tblusers_label_applications"]="Applications:";
$_LANG["tblusers_label_delete"]="Delete user";
$_LANG["tblusers_button_ok"]="Update";
$_LANG["tblusers_button_ok_title"]="Updates the record<br/>with the form data";
$_LANG["tblusers_button_cancel"]="Cancel";
$_LANG["tblusers_button_cancel_title"]="Cancels the on-going update";
$_LANG["tblusers_message_full_needed"]="It is necessary to provide all data";
$_LANG["tblusers_message_password_error"]="The provided passwords are different";
$_LANG["tblusers_message_username_exists"]="The user already exists";
$_LANG["tblusers_message_apps_needed"]="Select some application";
?>