<?php
/*
 ____  _     _        ___  ____
|  _ \| |__ (_)_ __  / _ \/ ___|
| |_) | '_ \| | '_ \| | | \___ \
|  _ <| | | | | | | | |_| |___) |
|_| \_\_| |_|_|_| |_|\___/|____/

RhinOS: Framework to develop Rich Internet Applications
Copyright (C) 2007-2016 by Josep Sanz Campderrós
More information in http://www.saltos.org or info@saltos.org

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
$_LANG=array("lang"=>"es");
// ABOUT
$_LANG["about_copyright"]="Este software se distribuye bajo los términos de la licencia GPL-3.0:";
$_LANG["about_link_project"]="Acceso al proyecto";
$_LANG["about_link_project_title"]="Acceder a la web del proyecto";
$_LANG["about_software"]="Este software usa los siguientes componentes:";
$_LANG["about_server_base"]="Servidor base:";
$_LANG["about_php_plugins"]="PHP plugins:";
$_LANG["about_javascript_base"]="Javascript base:";
$_LANG["about_jquery_plugins"]="JQuery plugins:";
$_LANG["about_server_plugins"]="Servidor plugins:";
$_LANG["about_vxinfo"]="<b>Nota</b>: (*) Algunos proyectos no especifican la versión concreta de la licencia que emplean";
$_LANG["about_button_return"]="Volver";
$_LANG["about_button_return_title"]="Para volver al menú principal";
$_LANG["about_developers"]="Desarrolladores";
$_LANG["about_translators"]="Traducciones";
// CATALOG
$_LANG["catalog_show_icons_search"]="Mostrar iconos con el texto:";
$_LANG["catalog_button_ok"]="Actualizar";
$_LANG["catalog_button_ok_title"]="Muestra todos los iconos<br/>que cumplen el filtro";
$_LANG["catalog_button_all"]="Mostrar todo";
$_LANG["catalog_button_all_title"]="Muestra todos los iconos<br/>quitando el filtro actual";
$_LANG["catalog_button_cancel"]="Cancelar";
$_LANG["catalog_button_cancel_title"]="Cancela la consulta de iconos actual";
// CONNECT
$_LANG["connect_checkdemo_unknown_type"]="Unknown check_demo type: ";
$_LANG["connect_message_file_not_found"]="Fichero no encontrado: ";
$_LANG["connect_message_dir_not_found"]="Directorio no encontrado: ";
$_LANG["connect_message_dir_not_writable"]="Directorio sin permisos de escritura: ";
$_LANG["connect_message_unknown_type"]="Unknown type ";
$_LANG["connect_message_db_schema_noedit"]="Campo noedit no encontrado en la tabla db_forms";
$_LANG["connect_message_db_schema_about"]="Añada esta linea en la configuración (seccion db_tables)<br/>&nbsp;ROW \"about.php\",\"Acerca de RhinOS\",\"Acerca de RhinOS\",\"102\",\"khelpcenter.png\"";
// CONTACT
$_LANG["contact_field_name"]="Nombre";
$_LANG["contact_field_email"]="Email";
$_LANG["contact_field_comments"]="Comentarios";
$_LANG["contact_button_ok"]="Enviar";
$_LANG["contact_button_ok_title"]="Tras rellenar el formulario,<br/>envia los datos";
$_LANG["contact_button_cancel"]="Cancelar";
$_LANG["contact_button_cancel_title"]="Cancela el envio del formulario";
$_LANG["contact_message_full"]="Debe entrar todos los campos para poder enviar el correo al soporte técnico";
$_LANG["contact_message_error"]="Se ha producido un error enviando el e-mail a ";
$_LANG["contact_message_ok"]="Se ha enviado un e-mail con los datos del formulario a ";
// DB_SPEC
$_LANG["db_spec_button_ok"]="Actualizar";
$_LANG["db_spec_button_ok_title"]="Al hacer clic, se realiza la actualización de la configuración";
$_LANG["db_spec_button_cancel"]="Cancelar";
$_LANG["db_spec_button_cancel_title"]="Cancela la actualización de la configuración";
$_LANG["db_spec_field_file"]="Fichero:";
$_LANG["db_spec_message_file_detected"]="Se ha detectado la existencia del fichero ";
$_LANG["db_spec_message_error"]="Se ha producido un error al subir el fichero al servidor";
$_LANG["db_spec_message_ok"]="Se ha actualizado correctamente la configuración";
$_LANG["db_spec_message_set_database"]="El tag DATABASE ya se ha establecido antes";
$_LANG["db_spec_message_diff_database"]="El tag DATABASE difiere con el nombre de la base de datos ";
$_LANG["db_spec_message_null_database"]="El tag DATABASE no puede ser nulo";
$_LANG["db_spec_message_null_table"]="El tag TABLE no puede ser nulo";
$_LANG["db_spec_message_set_spec"]="El tag SPEC ya se ha establecido antes";
$_LANG["db_spec_message_null_spec"]="El tag SPEC no puede ser nulo";
// EXPORT
$_LANG["export_message_unallowed"]="Esta pagina debe de llamarse desde un listado";
$_LANG["export_message_not_data"]="No hay datos a exportar";
$_LANG["export_label_list_of"]="Listado de ";
$_LANG["export_label_page_number"]="Página ";
$_LANG["export_label_not_file"]="[No hay fichero]";
$_LANG["export_label_not_photo"]="[No hay foto]";
$_LANG["export_label_yes"]="Si";
$_LANG["export_label_not"]="No";
$_LANG["export_label_photo_not_available"]="[Imagen no disponible]";
$_LANG["export_title_of"]="Exportar datos de ";
$_LANG["export_output_format"]="Formato de salida:";
$_LANG["export_output_format_pdf"]="(PDF) Acrobat Reader";
$_LANG["export_output_format_xls5"]="(XLS) Microsoft Excel 5";
$_LANG["export_output_format_xls7"]="(XLS) Microsoft Excel 2007";
$_LANG["export_output_format_csv"]="(CSV) Texto separado por comas";
$_LANG["export_output_format_zip"]="(ZIP) Zip con todas las imágenes";
$_LANG["export_separator_field"]="Separador de campos:";
$_LANG["export_separator_field_1"]="(;) Punto y coma";
$_LANG["export_separator_field_2"]="(,) Coma";
$_LANG["export_separator_field_3"]="(:) Dos puntos";
$_LANG["export_separator_field_4"]="(.) Punto";
$_LANG["export_first_line"]="Nombre de los campos:";
$_LANG["export_paginate_model"]="Modo de paginación:";
$_LANG["export_paginate_model_1"]="Poner un sólo registro en cada página";
$_LANG["export_paginate_model_0"]="Poner el máximo número registros en cada página";
$_LANG["export_fields_to_export"]="Campos a exportar:";
$_LANG["export_button_ok"]="Exportar";
$_LANG["export_button_ok_title"]="Al hacer clic, se realiza la exportación";
$_LANG["export_button_sel"]="Selección";
$_LANG["export_button_sel_title"]="Selecciona todos los campos<br/>o no selecciona ninguno";
$_LANG["export_button_cancel"]="Cancelar";
$_LANG["export_button_cancel_title"]="Cancela la exportación actual";
$_LANG["export_first_register"]="Empezar desde el registro";
$_LANG["export_total_registers"]="Total de registros a exportar";
// FORM
$_LANG["form_config_not_found"]="No se ha detectado configuración para este formulario";
$_LANG["form_message_form_error"]="Se han encontrado errores en el formulario";
// FUNCTIONS
$_LANG["functions_closebody_ismsie"]="Para mejorar su experiencia con esta aplicación, le recomendamos los siguientes navegadores:";
$_LANG["functions_putselect_default_option"]="Seleccione una opción";
$_LANG["functions_putselect_not_options"]="[No hay ninguna opción]";
$_LANG["functions_putselect_big_options"]="Filtro para el listado: ";
$_LANG["functions_putselect_big_options_number"]=" resultados";
$_LANG["functions_putselect_big_options_title"]="Atención!!!";
$_LANG["functions_putselect_big_options_description"]="El listado contiene demasiados resultados<br/>(concretamente #numero#) y por eso, debe<br/>proporcionar algún filtro para obtener<br/>una lista mas corta";
$_LANG["functions_putselect_ok_options_title"]="Enhorabuena";
$_LANG["functions_putselect_ok_options_description"]="Con el filtro entrado, hemos encontrado<br/>#numero# resultados y al no superar los #maximo#<br/>resultados, se los podemos mostrar";
$_LANG["functions_putselect_not_options_title"]="Atención!!!";
$_LANG["functions_putselect_not_options_description"]="El filtro entrado es demasiado restrictivo<br/>y no hemos encontrado ningún resultado<br/>que lo cumpla";
$_LANG["functions_putselect_big_options_message"]="Por favor, aplique un filtro más restrictivo";
$_LANG["functions_putselect_button_search"]="Buscar";
$_LANG["functions_putmultiselect_button_add"]="Seleccionar";
$_LANG["functions_putmultiselect_button_add_title"]="Selecciona los elementos marcados";
$_LANG["functions_putmultiselect_button_del"]="Deseleccionar";
$_LANG["functions_putmultiselect_button_del_title"]="Deselecciona los elementos marcados";
$_LANG["functions_putmultiselect_not_options"]="[No hay ninguna opción]";
$_LANG["functions_putmultiselect_big_options"]="Filtro para el listado: ";
$_LANG["functions_putmultiselect_big_options_number"]=" resultados";
$_LANG["functions_putmultiselect_big_options_title"]="Atención!!!";
$_LANG["functions_putmultiselect_big_options_description"]="El listado contiene demasiados resultados<br/>(concretamente #numero#) y por eso, debe<br/>proporcionar algún filtro para obtener<br/>una lista mas corta";
$_LANG["functions_putmultiselect_ok_options_title"]="Enhorabuena";
$_LANG["functions_putmultiselect_ok_options_description"]="Con el filtro entrado, hemos encontrado<br/>#numero# resultados y al no superar los #maximo#<br/>resultados, se los podemos mostrar";
$_LANG["functions_putmultiselect_not_options_title"]="Atención!!!";
$_LANG["functions_putmultiselect_not_options_description"]="El filtro entrado es demasiado restrictivo<br/>y no hemos encontrado ningún resultado<br/>que lo cumpla";
$_LANG["functions_putmultiselect_button_search"]="Buscar";
$_LANG["functions_putfile_name"]="Nombre:";
$_LANG["functions_putfile_size"]="Tamaño:";
$_LANG["functions_putfile_type"]="Tipo:";
$_LANG["functions_putfile_download"]="Descargar el fichero";
$_LANG["functions_putfile_delete"]="Eliminar este fichero";
$_LANG["functions_putfile_not_file"]="[No hay ningun fichero]";
$_LANG["functions_putfile_demo_disabled"]="(Prestación desactivada en modo DEMO)";
$_LANG["functions_putphoto_name"]="Nombre:";
$_LANG["functions_putphoto_size"]="Tamaño:";
$_LANG["functions_putphoto_type"]="Tipo:";
$_LANG["functions_putphoto_download"]="Descargar la foto";
$_LANG["functions_putphoto_preview"]="Preview:";
$_LANG["functions_putphoto_delete"]="Eliminar esta foto";
$_LANG["functions_putphoto_not_photo"]="[No hay ninguna foto]";
$_LANG["functions_putphoto_demo_disabled"]="(Prestación desactivada en modo DEMO)";
$_LANG["functions_putboolean_yes"]="Si";
$_LANG["functions_putboolean_not"]="No";
$_LANG["functions_getboolean_alt"]="Cambiar el valor de este campo";
$_LANG["functions_getboolean_yes"]="Si";
$_LANG["functions_getboolean_not"]="No";
$_LANG["functions_getlink_not_file"]="[No hay ningun fichero]";
$_LANG["functions_getlink_name"]="Nombre: ";
$_LANG["functions_getlink_size"]="Tamaño: ";
$_LANG["functions_getlink_type"]="Tipo: ";
$_LANG["functions_getselect_default_option"]="Seleccione una opción";
$_LANG["functions_getselect_not_options"]="[No hay opción]";
$_LANG["functions_getmultiselect_not_options"]="[No hay opción]";
$_LANG["functions_puterrores_warning"]="Atención:";
$_LANG["functions_puterrores_error"]="Error:";
$_LANG["functions_reparaformconfig_error"]="Atención: Error interno de la aplicación";
$_LANG["functions_finddependencies_error"]="Registro vinculado en ";
$_LANG["functions_msgbox_title"]="Mensaje del sistema";
$_LANG["functions_msgbox_button_close"]="Cerrar";
$_LANG["functions_msgbox_button_return"]="Volver";
$_LANG["functions_msgbox_button_continue"]="Continuar";
$_LANG["functions_putfloatmenu_title"]="MENU";
$_LANG["functions_showdatadinamic_unknown_type"]="Unknown dinamic type ";
$_LANG["functions_putcolor_button_open"]="Colores";
$_LANG["functions_putcolor_button_open_title"]="Haga clic aquí para abrir el selector de colores";
$_LANG["functions_putdate_button_open"]="Calendario";
$_LANG["functions_putdate_button_open_title"]="Haga clic aquí para abrir el calendario";
$_LANG["functions_putform_retype"]="Repita ";
$_LANG["functions_putform_time_button"]="Tiempo";
$_LANG["functions_putform_time_button_title"]="Entre la hora y minutos en el formato HH:MM";
$_LANG["functions_putform_field_needed"]="Campo obligatorio";
$_LANG["functions_putform_field_unique"]="Campo único";
$_LANG["functions_putform_field_optional"]="Campo opcional";
$_LANG["functions_putform_field_readonly"]="Campo automático";
$_LANG["functions_preparebuttons_default_option"]="Seleccione tipo";
$_LANG["functions_preparebuttons_button_add"]="Añadir";
$_LANG["functions_preparebuttons_button_add_title"]="Añade un nuevo campo dinámico";
$_LANG["functions_preparebuttons_button_delete"]="Borrar";
$_LANG["functions_preparebuttons_button_delete_title"]="Borrar este campo";
$_LANG["functions_preparebuttons_button_moveup"]="Subir";
$_LANG["functions_preparebuttons_button_moveup_title"]="Mueve este campo hacia arriba";
$_LANG["functions_preparebuttons_button_movedown"]="Bajar";
$_LANG["functions_preparebuttons_button_movedown_title"]="Mueve este campo hacia abajo";
$_LANG["functions_putajaxdinamic_message_max"]="No se pueden añadir más campos";
$_LANG["functions_putajaxdinamic_unknown_type"]="Unknown dinamic type ";
$_LANG["functions_putbuttons_button_create"]="Crear";
$_LANG["functions_putbuttons_button_create_title"]="Crea un registro con los<br/>datos del formulario";
$_LANG["functions_putbuttons_button_update"]="Actualizar";
$_LANG["functions_putbuttons_button_update_title"]="Actualiza el registro con<br/>los datos del formulario";
$_LANG["functions_putbuttons_button_create2"]="Crear y volver";
$_LANG["functions_putbuttons_button_create2_title"]="Crea un registro con los<br/>datos del formulario y<br/>retorna a esta pantalla";
$_LANG["functions_putbuttons_button_update2"]="Actualizar y volver";
$_LANG["functions_putbuttons_button_update2_title"]="Actualiza el registro con<br/>los datos del formulario y<br/>retorna a esta pantalla";
$_LANG["functions_putbuttons_button_cancel"]="Cancelar";
$_LANG["functions_putbuttons_button_cancel_create"]="Cancela la creación<br/>en curso";
$_LANG["functions_putbuttons_button_cancel_update"]="Cancela la actualización<br/>en curso";
$_LANG["functions_putbuttons_button_return"]="Volver";
$_LANG["functions_putbuttons_button_return_title"]="Para volver al listado anterior";
$_LANG["functions_putbuttons_button_update3"]="Editar";
$_LANG["functions_putbuttons_button_update3_title"]="Accede a la pantalla para<br/>editar todos los datos<br/>de este registro";
$_LANG["functions_checkmultipleparameters_message_diff_error"]="Los valores entrados en los campos #campo1# y Repita #campo2# son diferentes";
$_LANG["functions_checkmultipleparameters_message_unique_error"]="Existe un registro con el mismo valor en el campo ";
$_LANG["functions_checkmultipleparameters_message_needed_error"]="El campo #campo# es obligatorio";
$_LANG["functions_updatedatadinamic_message_error_type"]="Unknown dinamic type ";
$_LANG["functions_updatedatadinamic_message_error_counter"]="Unknown dinamic counter ";
$_LANG["functions_getmigas_button_menu"]="Menú principal";
$_LANG["functions_getmigas_button_menu_title"]="Acceso al menú principal";
$_LANG["functions_getmigas_button_access_to"]="Aplicación de ";
$_LANG["functions_getmigas_button_access_to_title"]="Acceso a la aplicación de ";
$_LANG["functions_getmigas_button_list"]="Listado de ";
$_LANG["functions_getmigas_button_list_title"]="Acceso al listado de ";
$_LANG["functions_getmigas_button_show"]="Consulta de ";
$_LANG["functions_getmigas_button_show_title"]="Acceso a la consulta de ";
$_LANG["functions_getmigas_button_update"]="Actualización de ";
$_LANG["functions_getmigas_button_update_title"]="Acceso a la actualización de ";
$_LANG["functions_getmigas_button_create"]="Creación de ";
$_LANG["functions_getmigas_button_create_title"]="Acceso a la creación de ";
$_LANG["functions_getmigas_button_export"]="Exportación de ";
$_LANG["functions_getmigas_button_export_title"]="Acceso a la exportación de ";
$_LANG["functions_getmigas_button_login"]="Acceso a la aplicación";
$_LANG["functions_getmigas_button_login_title"]="Esta pantalla permite acceder a la<br/>aplicación usando sus credenciales";
$_LANG["functions_getpartners_2_title"]="The SaltOS project";
$_LANG["functions_getpartners_2_description"]="Visite el portal del proyecto<br/>que hace posible este software";
$_LANG["functions_getpartners_3_title"]="Licensed unded GPL-3.0";
$_LANG["functions_getpartners_3_description"]="Este software esta licenciado<br/>bajo la licencia GPL-3.0";
$_LANG["functions_getpartners_4_title"]="Powered by GNU";
$_LANG["functions_getpartners_4_description"]="RhinOS basa toda su tecnologia de<br/>aplicaciones sobre sistemas GNU/Linux";
$_LANG["functions_getpartners_5_title"]="Powered by Apache";
$_LANG["functions_getpartners_5_description"]="RhinOS basa toda su tecnologia<br/>de aplicaciones web sobre Apache";
$_LANG["functions_getpartners_6_title"]="Powered by PHP";
$_LANG["functions_getpartners_6_description"]="RhinOS basa toda su tecnologia<br/>de aplicaciones web sobre PHP";
$_LANG["functions_getpartners_7_title"]="Powered by MySQL";
$_LANG["functions_getpartners_7_description"]="RhinOS basa toda su tecnologia<br/>de aplicaciones web sobre MySQL";
$_LANG["functions_getpartners_8_title"]="Powered by SQLite";
$_LANG["functions_getpartners_8_description"]="RhinOS basa toda su tecnologia<br/>de aplicaciones web sobre SQLite";
$_LANG["functions_getpartners_9_title"]="Powered by JQuery";
$_LANG["functions_getpartners_9_description"]="RhinOS usa la tecnologia de JQuery y JQuery UI<br/>para sus aplicaciones web";
$_LANG["functions_getpartners_10_title"]="Powered by PHPJS";
$_LANG["functions_getpartners_10_description"]="RhinOS usa la tecnologia de PHPJS<br/>pasa sus aplicaciones web";
$_LANG["functions_getpartners_11_title"]="Powered by CKEditor";
$_LANG["functions_getpartners_11_description"]="RhinOS usa la tecnologia de CKEditor<br/>pasa sus aplicaciones web";
$_LANG["functions_getpartners_12_title"]="Use Firefox";
$_LANG["functions_getpartners_12_description"]="Desde RhinOS, recomendamos el uso<br/>de este navegador para obtener las máximas<br/>prestaciones de las aplicaciones on-line";
$_LANG["functions_getpartners_13_title"]="Use Google Chrome";
$_LANG["functions_getpartners_13_description"]="Desde RhinOS, recomendamos el uso<br/>de este navegador para obtener las máximas<br/>prestaciones de las aplicaciones on-line";
$_LANG["functions_getloading_title"]="Cargando...";
$_LANG["functions_color2dec_error"]="Unknown component on color2dec function";
$_LANG["functions_addlog_error"]="Can not open log file: ";
// GETDINAMIC
$_LANG["getdinamic_unknown_type"]="Unknown dinamic type ";
$_LANG["getdinamic_demo_disabled"]="(Prestación desactivada en modo DEMO)";
// GETFILTER
$_LANG["getfilter_message_error"]="Atención: error interno de la aplicación";
// GETSELECT
$_LANG["getselect_button_date"]="Calendario";
$_LANG["getselect_button_date_title"]="Muestra la fecha en el formato DD/MM/AAAA";
$_LANG["getselect_button_time"]="Tiempo";
$_LANG["getselect_button_time_title"]="Muestra la hora y minutos en el formato HH:MM";
// HEAD
$_LANG["head_button_password"]="Cambiar contraseña";
$_LANG["head_button_password_title"]="Cambia su contraseña<br/>de la aplicación";
$_LANG["head_button_contact"]="Soporte técnico";
$_LANG["head_button_contact_title"]="Enviar un e-mail al soporte técnico<br/>con incidencias o sugerencias al<br/>administrador del sistema";
$_LANG["head_button_about"]="Acerca de RhinOS";
$_LANG["head_button_about_title"]="Conozca los creditos de RhinOS<br/>y los componentes que usa";
$_LANG["head_button_logout"]="Cerrar sesión";
$_LANG["head_button_logout_title"]="Cierra la sesión actual<br/>de la aplicación";
$_LANG["head_button_style"]="Tema";
$_LANG["head_button_style_title"]="Actualmente tiene el tema ";
$_LANG["head_confirm_logout"]="Desea desconectarse?";
$_LANG["head_confirm_button_yes"]="Si";
$_LANG["head_confirm_button_not"]="No";
// INTRO
$_LANG["intro_button_ok"]="Entrar";
$_LANG["intro_button_ok_title"]="Tras poner el usuario y contraseña,<br/>valida los datos";
$_LANG["intro_access_denied"]="Acceso denegado!!!";
$_LANG["intro_username"]="Usuario:";
$_LANG["intro_password"]="Clave:";
$_LANG["intro_remember"]="Recordar contraseña en este ordenador:";
$_LANG["intro_demo"]="Para entrar en modo DEMO:";
$_LANG["intro_demo_enabled"]="modo DEMO activado";
$_LANG["intro_demo_message"]="Ha accedido en modo DEMO con lo que ciertas prestaciones estaran desactivadas por motivos de seguridad";
$_LANG["intro_block_admin"]="admin bloqueado";
$_LANG["intro_register_globals"]="Detectada variable register_globals=1";
$_LANG["intro_zlib_output_compression"]="Detectada variable zlib.output_compression=1";
$_LANG["intro_config_not_found"]="No se ha encontrado ninguna aplicación";
// LIST
$_LANG["list_config_not_found"]="No se ha detectado configuración para este listado";
$_LANG["list_button_create"]="Crear";
$_LANG["list_button_create_title"]="Seleccione cuantos registros<br/>quiere crear y pulse este botón";
$_LANG["list_button_create_prefix"]="Crear registros: ";
$_LANG["list_button_first"]="Primera";
$_LANG["list_button_first_title"]="Primera página";
$_LANG["list_button_first_description"]="Muestra la primera página";
$_LANG["list_button_previous"]="Anterior";
$_LANG["list_button_previous_title"]="Página anterior";
$_LANG["list_button_previous_description"]="Muestra la página anterior";
$_LANG["list_button_next"]="Siguiente";
$_LANG["list_button_next_title"]="Página siguiente";
$_LANG["list_button_next_description"]="Muestra la página siguiente";
$_LANG["list_button_last"]="última";
$_LANG["list_button_last_title"]="última página";
$_LANG["list_button_last_description"]="Muestra la última página";
$_LANG["list_button_search"]="Buscar";
$_LANG["list_button_search_title"]="Busca todo lo que contenga<br/>el texto del buscador";
$_LANG["list_button_clear"]="Limpiar";
$_LANG["list_button_clear_title"]="Limpiar caja de texto";
$_LANG["list_button_clear_description"]="Limpia el contenido de la caja del buscador";
$_LANG["list_button_clear_prefix"]="Buscador: ";
$_LANG["list_button_fullpage"]="Lista completa";
$_LANG["list_button_fullpage_title"]="Muestra todos los resultados en una<br/>sola lista (#numero# registros en total)";
$_LANG["list_button_onlypage"]="Listar por páginas";
$_LANG["list_button_onlypage_title"]="Muestra los resultados por páginas<br/>(#numero# registros por página)";
$_LANG["list_label_sort_asc"]="ascendente";
$_LANG["list_label_sort_desc"]="descendente";
$_LANG["list_button_sort"]="Ordenar";
$_LANG["list_button_sort_title"]="Ordena la lista actual por<br/>";
$_LANG["list_label_not_file"]="[No hay fichero]";
$_LANG["list_label_not_photo"]="[No hay foto]";
$_LANG["list_icon_filter"]="Filtrar por ";
$_LANG["list_icon_filter_title"]="Muestra todos los registros<br/>con este/esta ";
$_LANG["list_icon_view"]="Consultar";
$_LANG["list_icon_view_title"]="Muestra todos los datos<br/>de este registro";
$_LANG["list_icon_edit"]="Editar";
$_LANG["list_icon_edit_title"]="Editar todos los datos<br/>de este registro";
$_LANG["list_icon_copy"]="Copiar";
$_LANG["list_icon_copy_title"]="Crea un registro nuevo con<br/>todos los datos de este registro";
$_LANG["list_icon_delete"]="Borrar";
$_LANG["list_icon_delete_title"]="Elimina este registro";
$_LANG["list_icon_save"]="Guardar";
$_LANG["list_icon_save_title"]="Guarda los cambios<br/>de este registro";
$_LANG["list_label_not_data"]="No hay datos a mostrar";
$_LANG["list_label_not_search"]="No se encontraron registros";
$_LANG["list_icon_selall"]="Seleccionar todos";
$_LANG["list_icon_selall_title"]="Marca como seleccionados<br/>todos los registros";
$_LANG["list_icon_selinv"]="Invertir seleccion";
$_LANG["list_icon_selinv_title"]="Invierte la seleccion<br/>de todos los registros";
$_LANG["list_icon_selnone"]="Deseleccionar todos";
$_LANG["list_icon_selnone_title"]="Marca como no seleccionados<br/>todos los registros";
$_LANG["list_icon_selview"]="Consultar seleccionados";
$_LANG["list_icon_selview_title"]="Muestra todos los datos<br/>de los registros seleccionados";
$_LANG["list_icon_seledit"]="Editar seleccionados";
$_LANG["list_icon_seledit_title"]="Editar todos los datos<br/>de los registros seleccionados";
$_LANG["list_icon_selcopy"]="Copiar seleccionados";
$_LANG["list_icon_selcopy_title"]="Crea registros nuevos con todos los<br/>datos de los registros seleccionados";
$_LANG["list_icon_seldelete"]="Borrar seleccionados";
$_LANG["list_icon_seldelete_title"]="Elimina todos los registros seleccionados";
$_LANG["list_icon_selsave"]="Guardar seleccionados";
$_LANG["list_icon_selsave_title"]="Guarda los cambios<br/>de los registros seleccionados";
$_LANG["list_label_reg_show"]="Registros mostrados: ";
$_LANG["list_label_reg_pag"]="Registros por página: ";
$_LANG["list_select_reg_show"]="Registros mostrados";
$_LANG["list_select_reg_show_title"]="Actualmente se están mostrando los registros<br/>del #numero1# al #numero2#. Seleccione otra opción de esta lista<br/>para cambiar de página rápidamente.";
$_LANG["list_select_reg_pag"]="Registros por página";
$_LANG["list_select_reg_pag_title"]="Actualmente se están mostrando #numero# registros<br/>por página. Seleccione otra opción de esta lista<br/>para cambiar el número de registros por página<br/>rápidamente.";
$_LANG["list_button_export"]="Exportar listado actual";
$_LANG["list_button_export_title"]="Exporta los datos del listado actual<br/>en formato PDF, Excel o CSV";
$_LANG["list_message_error"]="Se han producido errores";
$_LANG["list_confirm_delete"]="Desea eliminar este registro?";
$_LANG["list_confirm_update"]="Desea actualizar este registro?";
$_LANG["list_message_selreg"]="Debe seleccionar algun registro";
$_LANG["list_confirm_seldelete"]="Desea eliminar los registros seleccionados?";
$_LANG["list_confirm_selupdate"]="Desea actualizar los registros seleccionados?";
$_LANG["list_confirm_biglist"]="Va a mostrar #numero# registros. Desea continuar?";
$_LANG["list_confirm_button_yes"]="Si";
$_LANG["list_confirm_button_not"]="No";
// MAILER
$_LANG["mailer_invalid_address"]="Dirección de correo electrónico erronea";
// MAIN
$_LANG["main_message_denied"]="No tiene permisos para realizar esta acción";
$_LANG["main_message_maintenance"]="Página en mantenimiento, disculpe las molestias";
// PASSWORD
$_LANG["password_message_error_old"]="La contraseña antigua es incorrecta";
$_LANG["password_message_error_new"]="Las nuevas contraseñas son diferentes";
$_LANG["password_message_ok"]="Se ha actualizado correctamente la contraseña";
$_LANG["password_old_password"]="Antigua clave:";
$_LANG["password_new_password"]="Nueva clave:";
$_LANG["password_retype_new_password"]="Repita nueva clave:";
$_LANG["password_button_ok"]="Actualizar";
$_LANG["password_button_ok_title"]="Tras poner las contraseñas,<br/>realiza el cambio";
$_LANG["password_button_cancel"]="Cancelar";
$_LANG["password_button_cancel_title"]="Cancela el cambio de contraseñas";
// PROCESS
$_LANG["process_message_error_delete_needed"]="No se puede borrar un registro marcado como necesario";
$_LANG["process_message_error_nodata"]="No hay campos a actualizar";
$_LANG["process_message_error_unique"]="Existe un registro con el mismo valor en el campo ";
$_LANG["process_message_error_needed"]="El campo #campo# es obligatorio";
// TBL_CONFIG
$_LANG["tblconfig_title_create"]="Crear un nuevo parámetro de configuración";
$_LANG["tblconfig_title_delete"]="Borrar un parámetro de configuración";
$_LANG["tblconfig_message_fulldata_needed"]="Se necesitan los campos parámetro, tipo y título para esta opción";
$_LANG["tblconfig_button_ok"]="Actualizar";
$_LANG["tblconfig_button_ok_title"]="Actualiza el registro<br/>con los datos del formulario";
$_LANG["tblconfig_button_cancel"]="Cancelar";
$_LANG["tblconfig_button_cancel_title"]="Cancela la actualización en curso";
$_LANG["tblconfig_label_param"]="Parámetro:";
$_LANG["tblconfig_label_type"]="Tipo:";
$_LANG["tblconfig_option_text"]="Texto";
$_LANG["tblconfig_option_integer"]="Entero";
$_LANG["tblconfig_option_real"]="Real";
$_LANG["tblconfig_label_title"]="Título:";
$_LANG["tblconfig_label_minval"]="Valor mínimo:";
$_LANG["tblconfig_label_maxval"]="Valor máximo:";
$_LANG["tblconfig_title_managament"]="Gestione la configuración de su portal";
$_LANG["tblconfig_label_from_min_to_max"]="entre #minimo# y #maximo#";
$_LANG["tblconfig_label_from_min"]="a partir de #minimo#";
$_LANG["tblconfig_label_to_max"]="hasta #maximo#";
$_LANG["tblconfig_error_unknown_type"]="Unknown user space config type";
$_LANG["tblconfig_message_nodata"]="No hay datos de configuración en su portal";
$_LANG["tblconfig_label_delete"]="Parámetro a borrar:";
// TBL_FILES
$_LANG["tblfiles_title_create_file"]="Crear un nuevo fichero o foto";
$_LANG["tblfiles_title_delete_file"]="Borrar un nuevo fichero o foto";
$_LANG["tblfiles_title_current_files"]="Mantenimiento de los ficheros y fotos de su portal";
$_LANG["tblfiles_demo_disabled"]="Prestación desactivada en modo DEMO";
$_LANG["tblfiles_message_tag_exists"]="El tag que intenta crear ya existe";
$_LANG["tblfiles_button_ok"]="Actualizar";
$_LANG["tblfiles_button_ok_title"]="Actualiza el registro<br/>con los datos del formulario";
$_LANG["tblfiles_button_cancel"]="Cancelar";
$_LANG["tblfiles_button_cancel_title"]="Cancela la actualización en curso";
$_LANG["tblfiles_label_tag"]="Tag del fichero:";
$_LANG["tblfiles_label_isfile"]="Es una imagen:";
$_LANG["tblfiles_label_file"]="Fichero:";
$_LANG["tblfiles_label_delete"]="Borrar fichero o foto:";
$_LANG["tblfiles_label_photo"]="Foto:";
$_LANG["tblfiles_message_nodata"]="No hay ficheros parametrizados en su portal";
// TBL_GOOGLE
$_LANG["tblgoogle_button_ok"]="Actualizar";
$_LANG["tblgoogle_button_ok_title"]="Actualiza el registro<br/>con los datos del formulario";
$_LANG["tblgoogle_button_cancel"]="Cancelar";
$_LANG["tblgoogle_button_cancel_title"]="Cancela la actualización en curso";
$_LANG["tblgoogle_label_for"]=" para ";
$_LANG["tblgoogle_label_title"]="Configuración de Google Maps";
$_LANG["tblgoogle_label_lat"]="Latitud GPS:";
$_LANG["tblgoogle_label_lon"]="Longitud GPS:";
$_LANG["tblgoogle_label_logo"]="Logotipo:";
$_LANG["tblgoogle_label_text"]="Texto:";
// TBL_LABELS
$_LANG["tbllabels_title_table_options"]="Opciones de la tabla literales";
$_LANG["tbllabels_title_create_tag"]="Crear un nuevo literal";
$_LANG["tbllabels_title_delete_tag"]="Borrar un literal existente";
$_LANG["tbllabels_title_change_lang_sec"]="Cambiar de idioma o sección";
$_LANG["tbllabels_title_current_labels"]="Mantenimiento de los literales de su portal";
$_LANG["tbllabels_label_option_add_sec"]="Añadir seccion";
$_LANG["tbllabels_label_option_del_sec"]="Eliminar seccion";
$_LANG["tbllabels_label_option_add_lang"]="Añadir idioma";
$_LANG["tbllabels_label_option_del_lang"]="Eliminar idioma";
$_LANG["tbllabels_message_error_lang_with_not_option"]="No tiene sentido entrar un idioma sin especificar la opción asociada al idioma";
$_LANG["tbllabels_message_error_sec_not_lang"]="No se debe entrar el campo [idioma de la opción] para esta opción";
$_LANG["tbllabels_message_ok_add_sec"]="Se ha añadido el campo de secciones";
$_LANG["tbllabels_message_error_sec_exists"]="Ya existe el campo de secciones";
$_LANG["tbllabels_message_ok_del_sec"]="Se ha borrado el campo de secciones";
$_LANG["tbllabels_message_error_sec_not_exists"]="No existe el campo de secciones";
$_LANG["tbllabels_message_error_lang_not_found"]="Se debe entrar el campo [idioma de la opción] para esta opción";
$_LANG["tbllabels_message_error_lang_2_chars"]="El idioma debe tener 2 carácteres";
$_LANG["tbllabels_message_ok_add_lang"]="Se ha añadido el idioma ";
$_LANG["tbllabels_message_error_lang_exists"]="Ya existe el idioma ";
$_LANG["tbllabels_message_error_lang_del_default"]="No se puede borrar el idioma [#default#]";
$_LANG["tbllabels_message_ok_del_lang"]="Se ha borrado el idioma ";
$_LANG["tbllabels_message_error_lang_not_exists"]="No existe el idioma ";
$_LANG["tbllabels_message_error_tag_exists"]="El tag que intenta crear ya existe";
$_LANG["tbllabels_button_ok"]="Actualizar";
$_LANG["tbllabels_button_ok_title"]="Actualiza el registro<br/>con los datos del formulario";
$_LANG["tbllabels_button_cancel"]="Cancelar";
$_LANG["tbllabels_button_cancel_title"]="Cancela la actualización en curso";
$_LANG["tbllabels_label_literal"]="Valor del literal";
$_LANG["tbllabels_label_table_options"]="Opciones de la tabla:";
$_LANG["tbllabels_label_lang_option"]="Idioma de la opción:";
$_LANG["tbllabels_label_sec_exists"]="Existen secciones.";
$_LANG["tbllabels_label_sec_not_exists"]="No existen secciones.";
$_LANG["tbllabels_label_current_langs"]="Idiomas actuales: ";
$_LANG["tbllabels_label_notes"]="Notas: ";
$_LANG["tbllabels_label_new_literal"]="Nuevo literal:";
$_LANG["tbllabels_label_new_sec"]="Nueva sección:";
$_LANG["tbllabels_label_existent_sec"]="Sección existente:";
$_LANG["tbllabels_label_ishtml"]="Es un campo HTML:";
$_LANG["tbllabels_label_section"]="Sección:";
$_LANG["tbllabels_label_del_literal"]="Borrar literal:";
$_LANG["tbllabels_label_lang"]="Idioma:";
$_LANG["tbllabels_label_letter"]="Letra ";
$_LANG["tbllabels_message_nodata"]="No hay literales parametrizados en su portal";
// TBL_MAILING
$_LANG["tblmailing_demo_disabled"]="Prestación desactivada en modo DEMO";
$_LANG["tblmailing_message_error"]="Para enviar un mailing debe entrar todos los campos";
$_LANG["tblmailing_message_ok"]="El mailing ha sido aceptado para el envio";
$_LANG["tblmailing_button_ok"]="Actualizar";
$_LANG["tblmailing_button_ok_title"]="Actualiza el registro<br/>con los datos del formulario";
$_LANG["tblmailing_button_cancel"]="Cancelar";
$_LANG["tblmailing_button_cancel_title"]="Cancela la actualización en curso";
$_LANG["tblmailing_label_smtp_config"]="Configuración del servidor SMTP";
$_LANG["tblmailing_label_smtp_host"]="SMTP host:";
$_LANG["tblmailing_label_username"]="Username:";
$_LANG["tblmailing_label_password"]="Password:";
$_LANG["tblmailing_label_from_email"]="From email:";
$_LANG["tblmailing_label_from_name"]="From name:";
$_LANG["tblmailing_label_to"]="To:";
$_LANG["tblmailing_label_subject"]="Subject:";
$_LANG["tblmailing_label_body"]="Body:";
// TBL_USERS
$_LANG["tblusers_title_create"]="Crear un nuevo usuario:";
$_LANG["tblusers_title_modify"]="Modificar usuarios existentes:";
$_LANG["tblusers_label_username"]="Usuario:";
$_LANG["tblusers_label_password"]="Clave:";
$_LANG["tblusers_label_retype"]="Repita clave:";
$_LANG["tblusers_label_applications"]="Aplicaciones:";
$_LANG["tblusers_label_delete"]="Borrar usuario";
$_LANG["tblusers_button_ok"]="Actualizar";
$_LANG["tblusers_button_ok_title"]="Actualiza el registro<br/>con los datos del formulario";
$_LANG["tblusers_button_cancel"]="Cancelar";
$_LANG["tblusers_button_cancel_title"]="Cancela la actualización en curso";
$_LANG["tblusers_message_full_needed"]="Es necesario entrar todos los datos";
$_LANG["tblusers_message_password_error"]="Las claves entradas son diferentes";
$_LANG["tblusers_message_username_exists"]="El usuario que intenta crear ya existe";
$_LANG["tblusers_message_apps_needed"]="Es necesario seleccionar alguna aplicación";
?>